/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package UI;

import LogicaDeNegocios.CoordinadorDeInventario;

import java.awt.event.KeyEvent;
import java.sql.ResultSet;
import java.sql.SQLException;
import javax.swing.JOptionPane;
import javax.swing.table.DefaultTableModel;

/**
 *
 * @author usuario
 */
public class ControlDeExistenciasDeProductos extends javax.swing.JFrame {
 
  

    public ControlDeExistenciasDeProductos() {
        initComponents();
        setLocationRelativeTo(null);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jScrollPane3 = new javax.swing.JScrollPane();
        Tabla_ControlDeExistencias = new javax.swing.JTable();
        txtBuscarExistencias_ControlDeExistencias = new javax.swing.JTextField();
        btBuscar_ControlDeExistencias = new javax.swing.JButton();
        lbTitulo_ControlDeExistencias = new javax.swing.JLabel();
        lbIngresar_ControlDeExistencias = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);

        Tabla_ControlDeExistencias.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "Código", "Nombre", "Clasificación", "Existencias", "Precio", "UME"
            }
        ));
        jScrollPane3.setViewportView(Tabla_ControlDeExistencias);

        txtBuscarExistencias_ControlDeExistencias.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyTyped(java.awt.event.KeyEvent evt) {
                txtBuscarExistencias_ControlDeExistenciasKeyTyped(evt);
            }
        });

        btBuscar_ControlDeExistencias.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Imagenes/lupa-para-buscar.png"))); // NOI18N
        btBuscar_ControlDeExistencias.setToolTipText("Para buscar productos con existencias igual o menores a....");
        btBuscar_ControlDeExistencias.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btBuscar_ControlDeExistenciasActionPerformed(evt);
            }
        });

        lbTitulo_ControlDeExistencias.setFont(new java.awt.Font("Segoe Print", 1, 24)); // NOI18N
        lbTitulo_ControlDeExistencias.setText("Control de Existencias");

        lbIngresar_ControlDeExistencias.setText("Ingresar máximo:");

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(230, 230, 230)
                        .addComponent(lbIngresar_ControlDeExistencias)
                        .addGap(49, 49, 49)
                        .addComponent(txtBuscarExistencias_ControlDeExistencias, javax.swing.GroupLayout.PREFERRED_SIZE, 158, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(30, 30, 30)
                        .addComponent(btBuscar_ControlDeExistencias, javax.swing.GroupLayout.PREFERRED_SIZE, 50, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(269, 269, 269)
                        .addComponent(lbTitulo_ControlDeExistencias))
                    .addGroup(layout.createSequentialGroup()
                        .addContainerGap()
                        .addComponent(jScrollPane3, javax.swing.GroupLayout.PREFERRED_SIZE, 810, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap(15, Short.MAX_VALUE)
                .addComponent(lbTitulo_ControlDeExistencias)
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(btBuscar_ControlDeExistencias, javax.swing.GroupLayout.PREFERRED_SIZE, 45, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(8, 8, 8)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(txtBuscarExistencias_ControlDeExistencias, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(lbIngresar_ControlDeExistencias))))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jScrollPane3, javax.swing.GroupLayout.PREFERRED_SIZE, 289, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(16, 16, 16))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents
    public void btBuscar() {
       
        try {
            
             Object[] filas;
           DefaultTableModel modelo = new DefaultTableModel() {
                public boolean isCellEditable(int fila, int columna) {
                    return false;
                }
            };
            
            modelo.addColumn("Código");
            modelo.addColumn("Nombre");
            modelo.addColumn("Clasificación");
            modelo.addColumn("Existencias");
            modelo.addColumn("Precio");
            modelo.addColumn("UME");

            filas = new Object[modelo.getColumnCount()];
            CoordinadorDeInventario elCoordinador = new CoordinadorDeInventario();
            if (txtBuscarExistencias_ControlDeExistencias.getText() != null && txtBuscarExistencias_ControlDeExistencias.getText() != "") {
                

                    int cantidad = Integer.parseInt(txtBuscarExistencias_ControlDeExistencias.getText());

                    ResultSet resultadoConsulta = elCoordinador.ListarProductosPorExistencias(cantidad);
             
                    if (resultadoConsulta.next() && resultadoConsulta != null) { 
                        
                        resultadoConsulta.beforeFirst();
                        while (resultadoConsulta.next()) {
                            for (int i = 0; i < modelo.getColumnCount(); i++) {

                                filas[i] = resultadoConsulta.getObject(i + 1);

                            }
                            modelo.addRow(filas);

                        
                    }  
                }
                  Tabla_ControlDeExistencias.setModel(modelo);
            }
           
        } catch (SQLException ex) {
         JOptionPane.showMessageDialog(null, "No se pudo realizar la acción\n por problemas de conexión con la base de datos","ERROR",JOptionPane.ERROR_MESSAGE);
        } catch (ClassNotFoundException ex) {
             JOptionPane.showMessageDialog(null, "No se pudo realizar la acción\n por problemas al encontrar la clase","ERROR",JOptionPane.ERROR_MESSAGE);
        }

    }

    public void txtBuscarExistencias(KeyEvent evt) {
        char c = evt.getKeyChar();

        if (!Character.isDigit(c)) {
            getToolkit().beep();

            evt.consume();

        }
    }
    private void txtBuscarExistencias_ControlDeExistenciasKeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txtBuscarExistencias_ControlDeExistenciasKeyTyped
        txtBuscarExistencias(evt);
    }//GEN-LAST:event_txtBuscarExistencias_ControlDeExistenciasKeyTyped

    private void btBuscar_ControlDeExistenciasActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btBuscar_ControlDeExistenciasActionPerformed
        btBuscar();
    }//GEN-LAST:event_btBuscar_ControlDeExistenciasActionPerformed
public static void VisualizarTodosProductos() {
        try {
              Object[] filas;
            DefaultTableModel modelo = new DefaultTableModel() {
                public boolean isCellEditable(int fila, int columna) {
                    return false;
                }
            };

            modelo.addColumn("Código");
            modelo.addColumn("Nombre");
            modelo.addColumn("Clasificación");
            modelo.addColumn("Existencias");
            modelo.addColumn("Precio");
            modelo.addColumn("UME");

            filas = new Object[modelo.getColumnCount()];
            CoordinadorDeInventario elCoordinador = new CoordinadorDeInventario();
            ResultSet resultadoConsulta = null;

            resultadoConsulta = elCoordinador.ListarProductos();
            if (resultadoConsulta.next() && resultadoConsulta != null) {
                resultadoConsulta.beforeFirst();
                while (resultadoConsulta.next()) {
                    for (int i = 0; i < modelo.getColumnCount(); i++) {

                        filas[i] = resultadoConsulta.getObject(i + 1);

                    }
                    modelo.addRow(filas);

                }
            }
            Tabla_ControlDeExistencias.setModel(modelo);
        } catch (SQLException ex) {

        } catch (ClassNotFoundException ex) {

        }

    }


    // Variables declaration - do not modify//GEN-BEGIN:variables
    public static javax.swing.JTable Tabla_ControlDeExistencias;
    private javax.swing.JButton btBuscar_ControlDeExistencias;
    private javax.swing.JScrollPane jScrollPane3;
    private javax.swing.JLabel lbIngresar_ControlDeExistencias;
    private javax.swing.JLabel lbTitulo_ControlDeExistencias;
    public static javax.swing.JTextField txtBuscarExistencias_ControlDeExistencias;
    // End of variables declaration//GEN-END:variables
}
