/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package UI;

import java.sql.SQLException;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.JOptionPane;
import javax.swing.JTextField;

/**
 *
 * @author Christian
 */
public class DetalleProductoDesechado extends javax.swing.JFrame {

    public static String NumeroFactura="";
    public static String CodigoProducto="";
    public static String NombreProducto="";
    public static int CantidadVendida=0;
    public static int CantidadParaDesechar=0;
    public static int CantidadMaximaParaVender=0;
    /**
     * Creates new form DetalleProductoDesechado
     */
    public DetalleProductoDesechado() {
        initComponents();
    }

    public DetalleProductoDesechado(String NumeroFactura,String CodigoProducto,String NombreProducto,int CantidadVendida,int CantidadMaximaParaVender) {
       initComponents();
        this.NumeroFactura=NumeroFactura;
        this.CodigoProducto=CodigoProducto;
        this.NombreProducto=NombreProducto;
        this.CantidadVendida=CantidadVendida;
        this.CantidadMaximaParaVender=CantidadMaximaParaVender;
        txtNumeroFactura_DetalleDesecho.setText(NumeroFactura);
        txtCodigoProducto_DetalleDesecho.setText(CodigoProducto);
        txtNombreProducto_DetalleDesecho.setText(NombreProducto);
        txtCantidadVendida_DetalleDesecho.setText(""+CantidadVendida);
        txtCantidadMxDevolver_DetalleDesecho.setText(""+CantidadMaximaParaVender);
    }
    
   

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        GrupoSeleccion = new javax.swing.ButtonGroup();
        MensajeDetalle = new javax.swing.JLabel();
        btAceptar_DetalleDesecho = new javax.swing.JButton();
        btCancelar_DetalleDesecho = new javax.swing.JButton();
        txtNumeroFactura_DetalleDesecho = new javax.swing.JTextField();
        jSeparator1 = new javax.swing.JSeparator();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        txtCantidadVendida_DetalleDesecho = new javax.swing.JTextField();
        txtNombreProducto_DetalleDesecho = new javax.swing.JTextField();
        txtCodigoProducto_DetalleDesecho = new javax.swing.JTextField();
        PanelDesecho_DetalleproductosDesechados = new javax.swing.JPanel();
        radiobtDesecharTodo_DetalleProductosDesechados = new javax.swing.JRadioButton();
        lbl_MensajeDevolverTodo = new javax.swing.JLabel();
        PanelDesechoParcial_DetalleproductosDesechados = new javax.swing.JPanel();
        radiobtDesecharUnaParte_DetalleProductosDesechados = new javax.swing.JRadioButton();
        lb_CantidadMaxima = new javax.swing.JLabel();
        txtCantidadMxDevolver_DetalleDesecho = new javax.swing.JTextField();
        lbl_CantidaParaDesechar = new javax.swing.JLabel();
        txtCantidadParaDevolver_DetalleDesecho = new javax.swing.JTextField();
        jLabel5 = new javax.swing.JLabel();
        jScrollPane1 = new javax.swing.JScrollPane();
        textAreaDetalleDesecho = new javax.swing.JTextArea();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);

        MensajeDetalle.setFont(new java.awt.Font("Lucida Fax", 3, 14)); // NOI18N
        MensajeDetalle.setForeground(new java.awt.Color(0, 102, 112));
        MensajeDetalle.setText("Ingrese el detalle del desecho");

        btAceptar_DetalleDesecho.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Imagenes/AcceptIcon.png"))); // NOI18N
        btAceptar_DetalleDesecho.setText("Aceptar");
        btAceptar_DetalleDesecho.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btAceptar_DetalleDesechoActionPerformed(evt);
            }
        });

        btCancelar_DetalleDesecho.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Imagenes/CancelIconn.png"))); // NOI18N
        btCancelar_DetalleDesecho.setText("Cancelar");
        btCancelar_DetalleDesecho.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btCancelar_DetalleDesechoActionPerformed(evt);
            }
        });

        txtNumeroFactura_DetalleDesecho.setFont(new java.awt.Font("Lucida Fax", 3, 24)); // NOI18N
        txtNumeroFactura_DetalleDesecho.setForeground(new java.awt.Color(0, 102, 112));
        txtNumeroFactura_DetalleDesecho.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        txtNumeroFactura_DetalleDesecho.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        txtNumeroFactura_DetalleDesecho.setDisabledTextColor(new java.awt.Color(0, 102, 112));
        txtNumeroFactura_DetalleDesecho.setEnabled(false);

        jSeparator1.setForeground(new java.awt.Color(0, 0, 0));

        jLabel2.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        jLabel2.setText("Código del producto: ");

        jLabel3.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        jLabel3.setText("Nombre del Producto:");

        jLabel4.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        jLabel4.setText("Cantidad Vendida:");

        txtCantidadVendida_DetalleDesecho.setFont(new java.awt.Font("Lucida Fax", 3, 12)); // NOI18N
        txtCantidadVendida_DetalleDesecho.setForeground(new java.awt.Color(0, 102, 112));
        txtCantidadVendida_DetalleDesecho.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        txtCantidadVendida_DetalleDesecho.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        txtCantidadVendida_DetalleDesecho.setDisabledTextColor(new java.awt.Color(0, 102, 112));
        txtCantidadVendida_DetalleDesecho.setEnabled(false);

        txtNombreProducto_DetalleDesecho.setFont(new java.awt.Font("Lucida Fax", 3, 12)); // NOI18N
        txtNombreProducto_DetalleDesecho.setForeground(new java.awt.Color(0, 102, 112));
        txtNombreProducto_DetalleDesecho.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        txtNombreProducto_DetalleDesecho.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        txtNombreProducto_DetalleDesecho.setDisabledTextColor(new java.awt.Color(0, 102, 112));
        txtNombreProducto_DetalleDesecho.setEnabled(false);

        txtCodigoProducto_DetalleDesecho.setFont(new java.awt.Font("Lucida Fax", 3, 12)); // NOI18N
        txtCodigoProducto_DetalleDesecho.setForeground(new java.awt.Color(0, 102, 112));
        txtCodigoProducto_DetalleDesecho.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        txtCodigoProducto_DetalleDesecho.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        txtCodigoProducto_DetalleDesecho.setDisabledTextColor(new java.awt.Color(0, 102, 112));
        txtCodigoProducto_DetalleDesecho.setEnabled(false);

        PanelDesecho_DetalleproductosDesechados.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));

        GrupoSeleccion.add(radiobtDesecharTodo_DetalleProductosDesechados);
        radiobtDesecharTodo_DetalleProductosDesechados.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        radiobtDesecharTodo_DetalleProductosDesechados.setText("Desechar todo ");
        radiobtDesecharTodo_DetalleProductosDesechados.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                radiobtDesecharTodo_DetalleProductosDesechadosMouseClicked(evt);
            }
        });
        radiobtDesecharTodo_DetalleProductosDesechados.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                radiobtDesecharTodo_DetalleProductosDesechadosActionPerformed(evt);
            }
        });

        lbl_MensajeDevolverTodo.setFont(new java.awt.Font("Lucida Fax", 3, 14)); // NOI18N
        lbl_MensajeDevolverTodo.setForeground(new java.awt.Color(0, 102, 112));
        lbl_MensajeDevolverTodo.setText("\"Se desechara toda la cantidad vendida del producto\"");
        lbl_MensajeDevolverTodo.setEnabled(false);

        javax.swing.GroupLayout PanelDesecho_DetalleproductosDesechadosLayout = new javax.swing.GroupLayout(PanelDesecho_DetalleproductosDesechados);
        PanelDesecho_DetalleproductosDesechados.setLayout(PanelDesecho_DetalleproductosDesechadosLayout);
        PanelDesecho_DetalleproductosDesechadosLayout.setHorizontalGroup(
            PanelDesecho_DetalleproductosDesechadosLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(PanelDesecho_DetalleproductosDesechadosLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(lbl_MensajeDevolverTodo, javax.swing.GroupLayout.PREFERRED_SIZE, 404, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, PanelDesecho_DetalleproductosDesechadosLayout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(radiobtDesecharTodo_DetalleProductosDesechados)
                .addGap(155, 155, 155))
        );
        PanelDesecho_DetalleproductosDesechadosLayout.setVerticalGroup(
            PanelDesecho_DetalleproductosDesechadosLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(PanelDesecho_DetalleproductosDesechadosLayout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(radiobtDesecharTodo_DetalleProductosDesechados)
                .addGap(18, 18, 18)
                .addComponent(lbl_MensajeDevolverTodo)
                .addGap(32, 32, 32))
        );

        PanelDesechoParcial_DetalleproductosDesechados.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));

        GrupoSeleccion.add(radiobtDesecharUnaParte_DetalleProductosDesechados);
        radiobtDesecharUnaParte_DetalleProductosDesechados.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        radiobtDesecharUnaParte_DetalleProductosDesechados.setText("Ingresar la cantidad a desechar");
        radiobtDesecharUnaParte_DetalleProductosDesechados.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                radiobtDesecharUnaParte_DetalleProductosDesechadosMouseClicked(evt);
            }
        });
        radiobtDesecharUnaParte_DetalleProductosDesechados.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                radiobtDesecharUnaParte_DetalleProductosDesechadosActionPerformed(evt);
            }
        });

        lb_CantidadMaxima.setFont(new java.awt.Font("Lucida Fax", 3, 12)); // NOI18N
        lb_CantidadMaxima.setForeground(new java.awt.Color(0, 102, 112));
        lb_CantidadMaxima.setText("Cantidad máxima a devolver: ");
        lb_CantidadMaxima.setEnabled(false);

        txtCantidadMxDevolver_DetalleDesecho.setFont(new java.awt.Font("Lucida Fax", 3, 12)); // NOI18N
        txtCantidadMxDevolver_DetalleDesecho.setForeground(new java.awt.Color(0, 102, 112));
        txtCantidadMxDevolver_DetalleDesecho.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        txtCantidadMxDevolver_DetalleDesecho.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        txtCantidadMxDevolver_DetalleDesecho.setDisabledTextColor(new java.awt.Color(0, 102, 112));
        txtCantidadMxDevolver_DetalleDesecho.setEnabled(false);

        lbl_CantidaParaDesechar.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        lbl_CantidaParaDesechar.setText("Cantidad para Desechar: ");
        lbl_CantidaParaDesechar.setEnabled(false);

        txtCantidadParaDevolver_DetalleDesecho.setFont(new java.awt.Font("Lucida Fax", 3, 12)); // NOI18N
        txtCantidadParaDevolver_DetalleDesecho.setForeground(new java.awt.Color(0, 102, 112));
        txtCantidadParaDevolver_DetalleDesecho.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        txtCantidadParaDevolver_DetalleDesecho.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        txtCantidadParaDevolver_DetalleDesecho.setDisabledTextColor(new java.awt.Color(0, 102, 112));
        txtCantidadParaDevolver_DetalleDesecho.setEnabled(false);
        txtCantidadParaDevolver_DetalleDesecho.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyTyped(java.awt.event.KeyEvent evt) {
                txtCantidadParaDevolver_DetalleDesechoKeyTyped(evt);
            }
        });

        javax.swing.GroupLayout PanelDesechoParcial_DetalleproductosDesechadosLayout = new javax.swing.GroupLayout(PanelDesechoParcial_DetalleproductosDesechados);
        PanelDesechoParcial_DetalleproductosDesechados.setLayout(PanelDesechoParcial_DetalleproductosDesechadosLayout);
        PanelDesechoParcial_DetalleproductosDesechadosLayout.setHorizontalGroup(
            PanelDesechoParcial_DetalleproductosDesechadosLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(PanelDesechoParcial_DetalleproductosDesechadosLayout.createSequentialGroup()
                .addContainerGap(46, Short.MAX_VALUE)
                .addGroup(PanelDesechoParcial_DetalleproductosDesechadosLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, PanelDesechoParcial_DetalleproductosDesechadosLayout.createSequentialGroup()
                        .addGroup(PanelDesechoParcial_DetalleproductosDesechadosLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addGroup(PanelDesechoParcial_DetalleproductosDesechadosLayout.createSequentialGroup()
                                .addComponent(lbl_CantidaParaDesechar)
                                .addGap(18, 18, 18)
                                .addComponent(txtCantidadParaDevolver_DetalleDesecho, javax.swing.GroupLayout.PREFERRED_SIZE, 111, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(PanelDesechoParcial_DetalleproductosDesechadosLayout.createSequentialGroup()
                                .addComponent(lb_CantidadMaxima)
                                .addGap(18, 18, 18)
                                .addComponent(txtCantidadMxDevolver_DetalleDesecho, javax.swing.GroupLayout.PREFERRED_SIZE, 69, javax.swing.GroupLayout.PREFERRED_SIZE)))
                        .addGap(26, 26, 26))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, PanelDesechoParcial_DetalleproductosDesechadosLayout.createSequentialGroup()
                        .addComponent(radiobtDesecharUnaParte_DetalleProductosDesechados)
                        .addGap(62, 62, 62))))
        );
        PanelDesechoParcial_DetalleproductosDesechadosLayout.setVerticalGroup(
            PanelDesechoParcial_DetalleproductosDesechadosLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(PanelDesechoParcial_DetalleproductosDesechadosLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(radiobtDesecharUnaParte_DetalleProductosDesechados)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGroup(PanelDesechoParcial_DetalleproductosDesechadosLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(txtCantidadMxDevolver_DetalleDesecho, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(lb_CantidadMaxima))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(PanelDesechoParcial_DetalleproductosDesechadosLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(txtCantidadParaDevolver_DetalleDesecho, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(lbl_CantidaParaDesechar))
                .addContainerGap())
        );

        jLabel5.setFont(new java.awt.Font("Lucida Fax", 3, 24)); // NOI18N
        jLabel5.setForeground(new java.awt.Color(0, 102, 112));
        jLabel5.setText("Desecho de Producto de la Factura Número:");

        textAreaDetalleDesecho.setColumns(20);
        textAreaDetalleDesecho.setRows(5);
        jScrollPane1.setViewportView(textAreaDetalleDesecho);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(607, 607, 607)
                        .addComponent(txtNumeroFactura_DetalleDesecho, javax.swing.GroupLayout.PREFERRED_SIZE, 165, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jSeparator1)
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(jLabel2, javax.swing.GroupLayout.PREFERRED_SIZE, 136, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addComponent(txtCodigoProducto_DetalleDesecho, javax.swing.GroupLayout.PREFERRED_SIZE, 83, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addComponent(jLabel3)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addComponent(txtNombreProducto_DetalleDesecho, javax.swing.GroupLayout.PREFERRED_SIZE, 237, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addComponent(jLabel4)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(txtCantidadVendida_DetalleDesecho, javax.swing.GroupLayout.PREFERRED_SIZE, 60, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(layout.createSequentialGroup()
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addGroup(layout.createSequentialGroup()
                                        .addComponent(PanelDesecho_DetalleproductosDesechados, javax.swing.GroupLayout.PREFERRED_SIZE, 425, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                        .addComponent(PanelDesechoParcial_DetalleproductosDesechados, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                                    .addGroup(layout.createSequentialGroup()
                                        .addGap(24, 24, 24)
                                        .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 742, javax.swing.GroupLayout.PREFERRED_SIZE)))
                                .addGap(0, 0, Short.MAX_VALUE)))
                        .addContainerGap())
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                        .addGap(0, 286, Short.MAX_VALUE)
                        .addComponent(MensajeDetalle, javax.swing.GroupLayout.PREFERRED_SIZE, 230, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(290, 290, 290))))
            .addGroup(layout.createSequentialGroup()
                .addGap(322, 322, 322)
                .addComponent(btCancelar_DetalleDesecho)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(btAceptar_DetalleDesecho)
                .addGap(0, 0, Short.MAX_VALUE))
            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(layout.createSequentialGroup()
                    .addGap(39, 39, 39)
                    .addComponent(jLabel5, javax.swing.GroupLayout.PREFERRED_SIZE, 558, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addContainerGap(219, Short.MAX_VALUE)))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(txtNumeroFactura_DetalleDesecho, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jSeparator1, javax.swing.GroupLayout.PREFERRED_SIZE, 8, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(jLabel2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(txtCodigoProducto_DetalleDesecho)
                        .addComponent(jLabel3)
                        .addComponent(txtNombreProducto_DetalleDesecho, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(jLabel4)
                        .addComponent(txtCantidadVendida_DetalleDesecho, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(PanelDesecho_DetalleproductosDesechados, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(PanelDesechoParcial_DetalleproductosDesechados, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(MensajeDetalle)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 54, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(btCancelar_DetalleDesecho)
                    .addComponent(btAceptar_DetalleDesecho))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(layout.createSequentialGroup()
                    .addGap(21, 21, 21)
                    .addComponent(jLabel5)
                    .addContainerGap(288, Short.MAX_VALUE)))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btCancelar_DetalleDesechoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btCancelar_DetalleDesechoActionPerformed
        // TODO add your handling code here:
        dispose();
    }//GEN-LAST:event_btCancelar_DetalleDesechoActionPerformed

    private void radiobtDesecharUnaParte_DetalleProductosDesechadosActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_radiobtDesecharUnaParte_DetalleProductosDesechadosActionPerformed
        // TODO add your handling code here:
        
    }//GEN-LAST:event_radiobtDesecharUnaParte_DetalleProductosDesechadosActionPerformed
int OpcionParaDesechar=0;
    private void radiobtDesecharUnaParte_DetalleProductosDesechadosMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_radiobtDesecharUnaParte_DetalleProductosDesechadosMouseClicked
        // TODO add your handling code here:
        lbl_MensajeDevolverTodo.setEnabled(false);
        lb_CantidadMaxima.setEnabled(true);
        lbl_CantidaParaDesechar.setEnabled(true);
        txtCantidadParaDevolver_DetalleDesecho.setEnabled(true);
        OpcionParaDesechar=1;
    }//GEN-LAST:event_radiobtDesecharUnaParte_DetalleProductosDesechadosMouseClicked

    private void radiobtDesecharTodo_DetalleProductosDesechadosMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_radiobtDesecharTodo_DetalleProductosDesechadosMouseClicked
        // TODO add your handling code here:
        
        txtCantidadParaDevolver_DetalleDesecho.setEnabled(false);
        lb_CantidadMaxima.setEnabled(false);
        lbl_CantidaParaDesechar.setEnabled(false);
        lbl_MensajeDevolverTodo.setEnabled(true);
        OpcionParaDesechar=2;
    }//GEN-LAST:event_radiobtDesecharTodo_DetalleProductosDesechadosMouseClicked

    private void btAceptar_DetalleDesechoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btAceptar_DetalleDesechoActionPerformed
       
      try{
            if(OpcionParaDesechar==0||textAreaDetalleDesecho.getText().equals("")){
            getToolkit().beep();
            JOptionPane.showMessageDialog(null, "Primero debe eligir una de las opciones o ingresar el detalle del desecho","ERROR",JOptionPane.ERROR_MESSAGE);
            return;
            }else{
                    if(OpcionParaDesechar==1){
                    
                    CantidadParaDesechar=Integer.parseInt(txtCantidadParaDevolver_DetalleDesecho.getText());
                                if(CantidadParaDesechar>CantidadMaximaParaVender){
                                   getToolkit().beep();
                                    JOptionPane.showMessageDialog(null, "Solo puede ingresar una cantidad menor a:"
                                    + " "+CantidadMaximaParaVender+"\nPor"
                                    + "favor vuelva a ingresar una cantidad menor, o seleccione otra opcion.","ERROR",JOptionPane.ERROR_MESSAGE);
                                    return;
                                    }else{
                                    AgregarProductosADesecho(CodigoProducto,NombreProducto,CantidadParaDesechar,textAreaDetalleDesecho.getText());
                                    }
                    }
                    else{
                    CantidadParaDesechar=CantidadMaximaParaVender;
                    AgregarProductosADesecho(CodigoProducto,NombreProducto,CantidadParaDesechar,textAreaDetalleDesecho.getText());
                    }
            }
            
            dispose();
        } catch (SQLException ex) {
            Logger.getLogger(DetalleProductoDesechado.class.getName()).log(Level.SEVERE, null, ex);
        }
    }//GEN-LAST:event_btAceptar_DetalleDesechoActionPerformed

    private void radiobtDesecharTodo_DetalleProductosDesechadosActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_radiobtDesecharTodo_DetalleProductosDesechadosActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_radiobtDesecharTodo_DetalleProductosDesechadosActionPerformed
String CantidadParaDesecharString;
    private void txtCantidadParaDevolver_DetalleDesechoKeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txtCantidadParaDevolver_DetalleDesechoKeyTyped
        // TODO add your handling code here:
         char tecla=evt.getKeyChar();
        if(Character.isLetter(tecla)){
            getToolkit().beep();
            evt.consume();
            JOptionPane.showMessageDialog(null, "Solo numeros","ERROR",JOptionPane.ERROR_MESSAGE);
        }
      
    }//GEN-LAST:event_txtCantidadParaDevolver_DetalleDesechoKeyTyped
 private void AgregarProductosADesecho(String CodigoProducto,String NombreProducto,int Cantidad, String Detalle)
      throws SQLException// metodo para mostrar la tabla co un parametro que tendra el resultado de la peticion
   {
       
       IngresarDevoluciones.ModeloProductosDesechados.setColumnIdentifiers(new Object[]{"Codigo Producto","Nombre Producto","Cantidad Desechada","Detalle"});
       IngresarDevoluciones.TablaProductosDesechados_Devoluciones.setModel(IngresarDevoluciones.ModeloProductosDesechados);
       
      
       try {
        
               IngresarDevoluciones.ModeloProductosDesechados.addRow(new Object[]{CodigoProducto,NombreProducto,Cantidad,Detalle});
               int CantidadRestante=Integer.parseInt(IngresarDevoluciones.TablaDetalleFacturaDeVenta_Devoluciones.getValueAt(IngresarDevoluciones.FilaSeleccionadaDetalleFactura, 3).toString());
               int ReusltadoResta=CantidadRestante-Cantidad;
               IngresarDevoluciones.TablaDetalleFacturaDeVenta_Devoluciones.setValueAt(ReusltadoResta, IngresarDevoluciones.FilaSeleccionadaDetalleFactura, 3);
       } catch (Exception e) {
       }
   }
    /**
     * @param args the command line arguments
     */
    

    // Variables declaration - do not modify//GEN-BEGIN:variables
    public static javax.swing.ButtonGroup GrupoSeleccion;
    public javax.swing.JLabel MensajeDetalle;
    public javax.swing.JPanel PanelDesechoParcial_DetalleproductosDesechados;
    public javax.swing.JPanel PanelDesecho_DetalleproductosDesechados;
    public javax.swing.JButton btAceptar_DetalleDesecho;
    public javax.swing.JButton btCancelar_DetalleDesecho;
    public javax.swing.JLabel jLabel2;
    public javax.swing.JLabel jLabel3;
    public javax.swing.JLabel jLabel4;
    public javax.swing.JLabel jLabel5;
    public javax.swing.JScrollPane jScrollPane1;
    public javax.swing.JSeparator jSeparator1;
    public javax.swing.JLabel lb_CantidadMaxima;
    public javax.swing.JLabel lbl_CantidaParaDesechar;
    public javax.swing.JLabel lbl_MensajeDevolverTodo;
    public javax.swing.JRadioButton radiobtDesecharTodo_DetalleProductosDesechados;
    public javax.swing.JRadioButton radiobtDesecharUnaParte_DetalleProductosDesechados;
    public javax.swing.JTextArea textAreaDetalleDesecho;
    public static javax.swing.JTextField txtCantidadMxDevolver_DetalleDesecho;
    public static javax.swing.JTextField txtCantidadParaDevolver_DetalleDesecho;
    public static javax.swing.JTextField txtCantidadVendida_DetalleDesecho;
    public static javax.swing.JTextField txtCodigoProducto_DetalleDesecho;
    public static javax.swing.JTextField txtNombreProducto_DetalleDesecho;
    public static javax.swing.JTextField txtNumeroFactura_DetalleDesecho;
    // End of variables declaration//GEN-END:variables
}
