/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package UI;

import java.sql.SQLException;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.JOptionPane;

/**
 *
 * @author Christian
 */
public class DetalleProductoReintegrados extends javax.swing.JFrame {

    /**
     * Creates new form DetalleProductoReintegrados
     */
    public static String NumeroFactura="";
    public static String CodigoProducto="";
    public static String NombreProducto="";
    public static float CantidadVendida=0;
    public static float CantidadParaReintegrar=0;
    public static float CantidadMaximaParaReintegrar=0;
  
    public DetalleProductoReintegrados() {
        initComponents();
    }
    
    public DetalleProductoReintegrados(String NumeroFactura,String CodigoProducto,String NombreProducto,float CantidadVendida,float CantidadMaximaParaReintegrar) {
       initComponents();
        this.NumeroFactura=NumeroFactura;
        this.CodigoProducto=CodigoProducto;
        this.NombreProducto=NombreProducto;
        this.CantidadVendida=CantidadVendida;
        this.CantidadMaximaParaReintegrar=CantidadMaximaParaReintegrar;
        txtNumeroFactura_DetalleProductosReintegrado.setText(NumeroFactura);
        txtCodigoProducto_DetalleProductosReintegrado.setText(CodigoProducto);
        txtNombreProducto_DetalleProductosReintegrado.setText(NombreProducto);
        txtCantidadVendida_DetalleProductosReintegrado.setText(""+CantidadVendida);
        txtCantidadMxDevolver_DetalleProductosReintegrado.setText(""+CantidadMaximaParaReintegrar);
    }
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        buttonGroup1 = new javax.swing.ButtonGroup();
        txtCantidadVendida_DetalleProductosReintegrado = new javax.swing.JTextField();
        txtNombreProducto_DetalleProductosReintegrado = new javax.swing.JTextField();
        txtCodigoProducto_DetalleProductosReintegrado = new javax.swing.JTextField();
        jLabel1 = new javax.swing.JLabel();
        PanelReintegrarTodo_DetalleProductosReintegrado = new javax.swing.JPanel();
        radiobtReintegrarTodo_DetalleProductosReintegrado = new javax.swing.JRadioButton();
        lbl_MensajeDevolverTodo = new javax.swing.JLabel();
        btAceptar_DetalleDesecho = new javax.swing.JButton();
        btCancelar_DetalleDesecho = new javax.swing.JButton();
        txtNumeroFactura_DetalleProductosReintegrado = new javax.swing.JTextField();
        PaneReintegroParcial_DetalleProductosReintegrado = new javax.swing.JPanel();
        radiobtReintegrarUnaParte_DetalleProductosReintegrado = new javax.swing.JRadioButton();
        lb_CantidadMaxima_DetalleProductosReintegrado = new javax.swing.JLabel();
        txtCantidadMxDevolver_DetalleProductosReintegrado = new javax.swing.JTextField();
        lbl_CantidaParaReintegrar = new javax.swing.JLabel();
        txtCantidadParaDevolver_DetalleProductosReintegrado = new javax.swing.JTextField();
        jSeparator1 = new javax.swing.JSeparator();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);

        txtCantidadVendida_DetalleProductosReintegrado.setFont(new java.awt.Font("Lucida Fax", 3, 12)); // NOI18N
        txtCantidadVendida_DetalleProductosReintegrado.setForeground(new java.awt.Color(0, 102, 112));
        txtCantidadVendida_DetalleProductosReintegrado.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        txtCantidadVendida_DetalleProductosReintegrado.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        txtCantidadVendida_DetalleProductosReintegrado.setDisabledTextColor(new java.awt.Color(0, 102, 112));
        txtCantidadVendida_DetalleProductosReintegrado.setEnabled(false);

        txtNombreProducto_DetalleProductosReintegrado.setFont(new java.awt.Font("Lucida Fax", 3, 12)); // NOI18N
        txtNombreProducto_DetalleProductosReintegrado.setForeground(new java.awt.Color(0, 102, 112));
        txtNombreProducto_DetalleProductosReintegrado.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        txtNombreProducto_DetalleProductosReintegrado.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        txtNombreProducto_DetalleProductosReintegrado.setDisabledTextColor(new java.awt.Color(0, 102, 112));
        txtNombreProducto_DetalleProductosReintegrado.setEnabled(false);

        txtCodigoProducto_DetalleProductosReintegrado.setFont(new java.awt.Font("Lucida Fax", 3, 12)); // NOI18N
        txtCodigoProducto_DetalleProductosReintegrado.setForeground(new java.awt.Color(0, 102, 112));
        txtCodigoProducto_DetalleProductosReintegrado.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        txtCodigoProducto_DetalleProductosReintegrado.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        txtCodigoProducto_DetalleProductosReintegrado.setDisabledTextColor(new java.awt.Color(0, 102, 112));
        txtCodigoProducto_DetalleProductosReintegrado.setEnabled(false);

        jLabel1.setFont(new java.awt.Font("Lucida Fax", 3, 24)); // NOI18N
        jLabel1.setForeground(new java.awt.Color(0, 102, 112));
        jLabel1.setText("Desecho de Producto de la Factura Número:");

        PanelReintegrarTodo_DetalleProductosReintegrado.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));

        buttonGroup1.add(radiobtReintegrarTodo_DetalleProductosReintegrado);
        radiobtReintegrarTodo_DetalleProductosReintegrado.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        radiobtReintegrarTodo_DetalleProductosReintegrado.setText("Reintegrar todo ");
        radiobtReintegrarTodo_DetalleProductosReintegrado.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                radiobtReintegrarTodo_DetalleProductosReintegradoMouseClicked(evt);
            }
        });
        radiobtReintegrarTodo_DetalleProductosReintegrado.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                radiobtReintegrarTodo_DetalleProductosReintegradoActionPerformed(evt);
            }
        });

        lbl_MensajeDevolverTodo.setFont(new java.awt.Font("Lucida Fax", 3, 14)); // NOI18N
        lbl_MensajeDevolverTodo.setForeground(new java.awt.Color(0, 102, 112));
        lbl_MensajeDevolverTodo.setText("\"Se devolvera toda la cantidad vendida del producto\"");
        lbl_MensajeDevolverTodo.setEnabled(false);

        javax.swing.GroupLayout PanelReintegrarTodo_DetalleProductosReintegradoLayout = new javax.swing.GroupLayout(PanelReintegrarTodo_DetalleProductosReintegrado);
        PanelReintegrarTodo_DetalleProductosReintegrado.setLayout(PanelReintegrarTodo_DetalleProductosReintegradoLayout);
        PanelReintegrarTodo_DetalleProductosReintegradoLayout.setHorizontalGroup(
            PanelReintegrarTodo_DetalleProductosReintegradoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(PanelReintegrarTodo_DetalleProductosReintegradoLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(lbl_MensajeDevolverTodo, javax.swing.GroupLayout.PREFERRED_SIZE, 404, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, PanelReintegrarTodo_DetalleProductosReintegradoLayout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(radiobtReintegrarTodo_DetalleProductosReintegrado)
                .addGap(155, 155, 155))
        );
        PanelReintegrarTodo_DetalleProductosReintegradoLayout.setVerticalGroup(
            PanelReintegrarTodo_DetalleProductosReintegradoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(PanelReintegrarTodo_DetalleProductosReintegradoLayout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(radiobtReintegrarTodo_DetalleProductosReintegrado)
                .addGap(18, 18, 18)
                .addComponent(lbl_MensajeDevolverTodo)
                .addGap(32, 32, 32))
        );

        btAceptar_DetalleDesecho.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Imagenes/AcceptIcon.png"))); // NOI18N
        btAceptar_DetalleDesecho.setText("Aceptar");
        btAceptar_DetalleDesecho.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btAceptar_DetalleDesechoActionPerformed(evt);
            }
        });

        btCancelar_DetalleDesecho.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Imagenes/CancelIconn.png"))); // NOI18N
        btCancelar_DetalleDesecho.setText("Cancelar");
        btCancelar_DetalleDesecho.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btCancelar_DetalleDesechoActionPerformed(evt);
            }
        });

        txtNumeroFactura_DetalleProductosReintegrado.setFont(new java.awt.Font("Lucida Fax", 3, 24)); // NOI18N
        txtNumeroFactura_DetalleProductosReintegrado.setForeground(new java.awt.Color(0, 102, 112));
        txtNumeroFactura_DetalleProductosReintegrado.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        txtNumeroFactura_DetalleProductosReintegrado.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        txtNumeroFactura_DetalleProductosReintegrado.setDisabledTextColor(new java.awt.Color(0, 102, 112));
        txtNumeroFactura_DetalleProductosReintegrado.setEnabled(false);

        PaneReintegroParcial_DetalleProductosReintegrado.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));

        buttonGroup1.add(radiobtReintegrarUnaParte_DetalleProductosReintegrado);
        radiobtReintegrarUnaParte_DetalleProductosReintegrado.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        radiobtReintegrarUnaParte_DetalleProductosReintegrado.setText("Ingresar la cantidad a reintegrar");
        radiobtReintegrarUnaParte_DetalleProductosReintegrado.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                radiobtReintegrarUnaParte_DetalleProductosReintegradoMouseClicked(evt);
            }
        });
        radiobtReintegrarUnaParte_DetalleProductosReintegrado.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                radiobtReintegrarUnaParte_DetalleProductosReintegradoActionPerformed(evt);
            }
        });

        lb_CantidadMaxima_DetalleProductosReintegrado.setFont(new java.awt.Font("Lucida Fax", 3, 12)); // NOI18N
        lb_CantidadMaxima_DetalleProductosReintegrado.setForeground(new java.awt.Color(0, 102, 112));
        lb_CantidadMaxima_DetalleProductosReintegrado.setText("Cantidad máxima a reintegrar: ");
        lb_CantidadMaxima_DetalleProductosReintegrado.setEnabled(false);

        txtCantidadMxDevolver_DetalleProductosReintegrado.setFont(new java.awt.Font("Lucida Fax", 3, 12)); // NOI18N
        txtCantidadMxDevolver_DetalleProductosReintegrado.setForeground(new java.awt.Color(0, 102, 112));
        txtCantidadMxDevolver_DetalleProductosReintegrado.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        txtCantidadMxDevolver_DetalleProductosReintegrado.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        txtCantidadMxDevolver_DetalleProductosReintegrado.setDisabledTextColor(new java.awt.Color(0, 102, 112));
        txtCantidadMxDevolver_DetalleProductosReintegrado.setEnabled(false);

        lbl_CantidaParaReintegrar.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        lbl_CantidaParaReintegrar.setText("Cantidad para Reintegrar: ");
        lbl_CantidaParaReintegrar.setEnabled(false);

        txtCantidadParaDevolver_DetalleProductosReintegrado.setFont(new java.awt.Font("Lucida Fax", 3, 12)); // NOI18N
        txtCantidadParaDevolver_DetalleProductosReintegrado.setForeground(new java.awt.Color(0, 102, 112));
        txtCantidadParaDevolver_DetalleProductosReintegrado.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        txtCantidadParaDevolver_DetalleProductosReintegrado.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        txtCantidadParaDevolver_DetalleProductosReintegrado.setDisabledTextColor(new java.awt.Color(0, 102, 112));
        txtCantidadParaDevolver_DetalleProductosReintegrado.setEnabled(false);
        txtCantidadParaDevolver_DetalleProductosReintegrado.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyTyped(java.awt.event.KeyEvent evt) {
                txtCantidadParaDevolver_DetalleProductosReintegradoKeyTyped(evt);
            }
        });

        javax.swing.GroupLayout PaneReintegroParcial_DetalleProductosReintegradoLayout = new javax.swing.GroupLayout(PaneReintegroParcial_DetalleProductosReintegrado);
        PaneReintegroParcial_DetalleProductosReintegrado.setLayout(PaneReintegroParcial_DetalleProductosReintegradoLayout);
        PaneReintegroParcial_DetalleProductosReintegradoLayout.setHorizontalGroup(
            PaneReintegroParcial_DetalleProductosReintegradoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(PaneReintegroParcial_DetalleProductosReintegradoLayout.createSequentialGroup()
                .addContainerGap(46, Short.MAX_VALUE)
                .addGroup(PaneReintegroParcial_DetalleProductosReintegradoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, PaneReintegroParcial_DetalleProductosReintegradoLayout.createSequentialGroup()
                        .addGroup(PaneReintegroParcial_DetalleProductosReintegradoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addGroup(PaneReintegroParcial_DetalleProductosReintegradoLayout.createSequentialGroup()
                                .addComponent(lbl_CantidaParaReintegrar)
                                .addGap(18, 18, 18)
                                .addComponent(txtCantidadParaDevolver_DetalleProductosReintegrado, javax.swing.GroupLayout.PREFERRED_SIZE, 111, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(PaneReintegroParcial_DetalleProductosReintegradoLayout.createSequentialGroup()
                                .addComponent(lb_CantidadMaxima_DetalleProductosReintegrado)
                                .addGap(18, 18, 18)
                                .addComponent(txtCantidadMxDevolver_DetalleProductosReintegrado, javax.swing.GroupLayout.PREFERRED_SIZE, 69, javax.swing.GroupLayout.PREFERRED_SIZE)))
                        .addGap(26, 26, 26))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, PaneReintegroParcial_DetalleProductosReintegradoLayout.createSequentialGroup()
                        .addComponent(radiobtReintegrarUnaParte_DetalleProductosReintegrado)
                        .addGap(62, 62, 62))))
        );
        PaneReintegroParcial_DetalleProductosReintegradoLayout.setVerticalGroup(
            PaneReintegroParcial_DetalleProductosReintegradoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(PaneReintegroParcial_DetalleProductosReintegradoLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(radiobtReintegrarUnaParte_DetalleProductosReintegrado)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGroup(PaneReintegroParcial_DetalleProductosReintegradoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(txtCantidadMxDevolver_DetalleProductosReintegrado, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(lb_CantidadMaxima_DetalleProductosReintegrado))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(PaneReintegroParcial_DetalleProductosReintegradoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(txtCantidadParaDevolver_DetalleProductosReintegrado, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(lbl_CantidaParaReintegrar))
                .addContainerGap())
        );

        jSeparator1.setForeground(new java.awt.Color(0, 0, 0));

        jLabel2.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        jLabel2.setText("Código del producto: ");

        jLabel3.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        jLabel3.setText("Nombre del Producto:");

        jLabel4.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        jLabel4.setText("Cantidad Vendida:");

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(306, 306, 306)
                .addComponent(btCancelar_DetalleDesecho)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(btAceptar_DetalleDesecho)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(19, 19, 19)
                        .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 558, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(30, 30, 30)
                        .addComponent(txtNumeroFactura_DetalleProductosReintegrado, javax.swing.GroupLayout.PREFERRED_SIZE, 165, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jSeparator1)
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(jLabel2, javax.swing.GroupLayout.PREFERRED_SIZE, 136, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addComponent(txtCodigoProducto_DetalleProductosReintegrado, javax.swing.GroupLayout.PREFERRED_SIZE, 83, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addComponent(jLabel3)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addComponent(txtNombreProducto_DetalleProductosReintegrado, javax.swing.GroupLayout.PREFERRED_SIZE, 237, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addComponent(jLabel4)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(txtCantidadVendida_DetalleProductosReintegrado, javax.swing.GroupLayout.PREFERRED_SIZE, 60, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                                .addComponent(PanelReintegrarTodo_DetalleProductosReintegrado, javax.swing.GroupLayout.PREFERRED_SIZE, 425, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(PaneReintegroParcial_DetalleProductosReintegrado, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(0, 0, Short.MAX_VALUE)))
                        .addContainerGap())))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel1)
                    .addComponent(txtNumeroFactura_DetalleProductosReintegrado, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jSeparator1, javax.swing.GroupLayout.PREFERRED_SIZE, 8, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(jLabel2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(txtCodigoProducto_DetalleProductosReintegrado)
                        .addComponent(jLabel3)
                        .addComponent(txtNombreProducto_DetalleProductosReintegrado, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(jLabel4)
                        .addComponent(txtCantidadVendida_DetalleProductosReintegrado, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(PanelReintegrarTodo_DetalleProductosReintegrado, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(PaneReintegroParcial_DetalleProductosReintegrado, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(btCancelar_DetalleDesecho)
                    .addComponent(btAceptar_DetalleDesecho))
                .addContainerGap())
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void radiobtReintegrarTodo_DetalleProductosReintegradoMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_radiobtReintegrarTodo_DetalleProductosReintegradoMouseClicked
        // TODO add your handling code here:

        txtCantidadParaDevolver_DetalleProductosReintegrado.setEnabled(false);
        lb_CantidadMaxima_DetalleProductosReintegrado.setEnabled(false);
        lbl_CantidaParaReintegrar.setEnabled(false);
        lbl_MensajeDevolverTodo.setEnabled(true);
        OpcionParaReintegrar=2;
    }//GEN-LAST:event_radiobtReintegrarTodo_DetalleProductosReintegradoMouseClicked

    private void radiobtReintegrarTodo_DetalleProductosReintegradoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_radiobtReintegrarTodo_DetalleProductosReintegradoActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_radiobtReintegrarTodo_DetalleProductosReintegradoActionPerformed

    private void btAceptar_DetalleDesechoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btAceptar_DetalleDesechoActionPerformed

        try{
            if(OpcionParaReintegrar==0){
                getToolkit().beep();
                JOptionPane.showMessageDialog(null, "Primero debe eligir una de las ","ERROR",JOptionPane.ERROR_MESSAGE);
                return;
            }else{
                if(OpcionParaReintegrar==1){
                            if(txtCantidadParaDevolver_DetalleProductosReintegrado.getText().equals("")){
                            getToolkit().beep();
                        JOptionPane.showMessageDialog(null, "Por favor ingrese una cantidad a reintegrar","ERROR",JOptionPane.ERROR_MESSAGE);
                        return;
                            
                            }else 
                            
                            {CantidadParaReintegrar=Integer.parseInt(txtCantidadParaDevolver_DetalleProductosReintegrado.getText());
                    if(CantidadParaReintegrar>CantidadMaximaParaReintegrar){
                        getToolkit().beep();
                        JOptionPane.showMessageDialog(null, "Solo puede ingresar una cantidad menor a:"
                            + " "+CantidadMaximaParaReintegrar+"\nPor"
                            + "favor vuelva a ingresar una cantidad menor, o seleccione otra opcion.","ERROR",JOptionPane.ERROR_MESSAGE);
                        return;
                    }else{
                        AgregarProductosAReintegro(CodigoProducto,NombreProducto,CantidadParaReintegrar);
                    }
                }}
                    
                else{
                    CantidadParaReintegrar=CantidadMaximaParaReintegrar;
                    AgregarProductosAReintegro(CodigoProducto,NombreProducto,CantidadParaReintegrar);
                }
            }

            dispose();
        } catch (SQLException ex) {
            Logger.getLogger(DetalleProductoDesechado.class.getName()).log(Level.SEVERE, null, ex);
        }
    }//GEN-LAST:event_btAceptar_DetalleDesechoActionPerformed

    private void btCancelar_DetalleDesechoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btCancelar_DetalleDesechoActionPerformed
        // TODO add your handling code here:
        dispose();
    }//GEN-LAST:event_btCancelar_DetalleDesechoActionPerformed
int OpcionParaReintegrar=0;
    private void radiobtReintegrarUnaParte_DetalleProductosReintegradoMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_radiobtReintegrarUnaParte_DetalleProductosReintegradoMouseClicked
        // TODO add your handling code here:
        lbl_MensajeDevolverTodo.setEnabled(false);
        lb_CantidadMaxima_DetalleProductosReintegrado.setEnabled(true);
        lbl_CantidaParaReintegrar.setEnabled(true);
        txtCantidadParaDevolver_DetalleProductosReintegrado.setEnabled(true);
        OpcionParaReintegrar = 1;
    }//GEN-LAST:event_radiobtReintegrarUnaParte_DetalleProductosReintegradoMouseClicked

    private void radiobtReintegrarUnaParte_DetalleProductosReintegradoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_radiobtReintegrarUnaParte_DetalleProductosReintegradoActionPerformed
        // TODO add your handling code here:

    }//GEN-LAST:event_radiobtReintegrarUnaParte_DetalleProductosReintegradoActionPerformed

    private void txtCantidadParaDevolver_DetalleProductosReintegradoKeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txtCantidadParaDevolver_DetalleProductosReintegradoKeyTyped
        // TODO add your handling code here:
        char tecla=evt.getKeyChar();
        if(Character.isLetter(tecla)){
            getToolkit().beep();
            evt.consume();
            JOptionPane.showMessageDialog(null, "Solo numeros","ERROR",JOptionPane.ERROR_MESSAGE);
        }

    }//GEN-LAST:event_txtCantidadParaDevolver_DetalleProductosReintegradoKeyTyped

    /**
     * @param args the command line arguments
     */

private void AgregarProductosAReintegro(String CodigoProducto,String NombreProducto,float Cantidad)
      throws SQLException// metodo para mostrar la tabla co un parametro que tendra el resultado de la peticion
   {
       
       IngresarDevoluciones.ModeloProductosReintegrados.setColumnIdentifiers(new Object[]{"Codigo Producto","Nombre Producto","Cantidad Reintegrada"});
       IngresarDevoluciones.TablaReintegro_Devoluciones.setModel(IngresarDevoluciones.ModeloProductosReintegrados);
       
      
       try {
        
               IngresarDevoluciones.ModeloProductosReintegrados.addRow(new Object[]{CodigoProducto,NombreProducto,Cantidad});
               float CantidadRestante=Float.parseFloat(IngresarDevoluciones.TablaDetalleFacturaDeVenta_Devoluciones.getValueAt(IngresarDevoluciones.FilaSeleccionadaDetalleFactura, 3).toString());
               float ReusltadoResta=CantidadRestante-Cantidad;
               IngresarDevoluciones.TablaDetalleFacturaDeVenta_Devoluciones.setValueAt(ReusltadoResta, IngresarDevoluciones.FilaSeleccionadaDetalleFactura, 3);
       } catch (Exception e) {
       }
   }
    // Variables declaration - do not modify//GEN-BEGIN:variables
    public javax.swing.JPanel PaneReintegroParcial_DetalleProductosReintegrado;
    public javax.swing.JPanel PanelReintegrarTodo_DetalleProductosReintegrado;
    public javax.swing.JButton btAceptar_DetalleDesecho;
    public javax.swing.JButton btCancelar_DetalleDesecho;
    public javax.swing.ButtonGroup buttonGroup1;
    public javax.swing.JLabel jLabel1;
    public javax.swing.JLabel jLabel2;
    public javax.swing.JLabel jLabel3;
    public javax.swing.JLabel jLabel4;
    public javax.swing.JSeparator jSeparator1;
    public javax.swing.JLabel lb_CantidadMaxima_DetalleProductosReintegrado;
    public javax.swing.JLabel lbl_CantidaParaReintegrar;
    public javax.swing.JLabel lbl_MensajeDevolverTodo;
    public javax.swing.JRadioButton radiobtReintegrarTodo_DetalleProductosReintegrado;
    public javax.swing.JRadioButton radiobtReintegrarUnaParte_DetalleProductosReintegrado;
    public static javax.swing.JTextField txtCantidadMxDevolver_DetalleProductosReintegrado;
    public static javax.swing.JTextField txtCantidadParaDevolver_DetalleProductosReintegrado;
    public static javax.swing.JTextField txtCantidadVendida_DetalleProductosReintegrado;
    public static javax.swing.JTextField txtCodigoProducto_DetalleProductosReintegrado;
    public static javax.swing.JTextField txtNombreProducto_DetalleProductosReintegrado;
    public static javax.swing.JTextField txtNumeroFactura_DetalleProductosReintegrado;
    // End of variables declaration//GEN-END:variables
}
