/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package UI;

import LogicaDeNegocios.CoordinadorDeCamion;
import Modelos.Carga;
import java.sql.ResultSet;
import java.sql.SQLException;
import java.text.SimpleDateFormat;
import java.util.Date;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.JOptionPane;

/**
 *
 * @author usuario
 */
public class EditarCarga extends javax.swing.JFrame {

    /**
     * Creates new form EditarCarga
     */
    public static String PlacaDeCamion="";
    public static Date FechaCarga;
    public static int IdCarga=0;
   

    public EditarCarga(String PlacaCamion, Date FechaCarga, int idCamion) throws ClassNotFoundException{
        initComponents();
        this.PlacaDeCamion=PlacaCamion;
        this.FechaCarga=FechaCarga;
        this.IdCarga=idCamion;
        txtIdCarga_EditarCarga.setText(""+IdCarga);
        DateFechaCarga_EditarCarga.setDate(FechaCarga);
        ListarTodasLasPlacas();
       jComboPlacas_EditarCarga.setSelectedItem(PlacaDeCamion);
    }

    
    public static void ListarTodasLasPlacas() {
        try {
            CoordinadorDeCamion elCoordinador = new CoordinadorDeCamion();
            ResultSet resultadoConsulta = elCoordinador.ListarTodasLasPlacas();
            if (resultadoConsulta == null) {
                JOptionPane.showMessageDialog(null, "Verifique que tenga permisos de administrador", "Error de permisos", JOptionPane.ERROR_MESSAGE);
                return;
            }
            while (resultadoConsulta.next()) {
                jComboPlacas_EditarCarga.addItem(resultadoConsulta.getString(1));
            }
        } catch (SQLException ex) {

        }catch (ClassNotFoundException ex) {

        }


    }
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        txtIdCarga_EditarCarga = new javax.swing.JTextField();
        jComboPlacas_EditarCarga = new javax.swing.JComboBox<String>();
        DateFechaCarga_EditarCarga = new com.toedter.calendar.JDateChooser();
        btAceptar_EditarCarga = new javax.swing.JButton();
        btSalir_EditarCarga = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);

        jLabel1.setFont(new java.awt.Font("Segoe Print", 1, 18)); // NOI18N
        jLabel1.setText("Editar Carga");

        jLabel2.setText("Id de Carga:");

        jLabel3.setText("Placa de Camión:");

        jLabel4.setText("Fecha de Carga:");

        txtIdCarga_EditarCarga.setEnabled(false);

        jComboPlacas_EditarCarga.setModel(new javax.swing.DefaultComboBoxModel(new String[] { "Seleccione..." }));

        btAceptar_EditarCarga.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Imagenes/Check_Icon_32.png"))); // NOI18N
        btAceptar_EditarCarga.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btAceptar_EditarCargaActionPerformed(evt);
            }
        });

        btSalir_EditarCarga.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Imagenes/Delete_Icon_32.png"))); // NOI18N
        btSalir_EditarCarga.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btSalir_EditarCargaActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(154, 154, 154)
                        .addComponent(jLabel1)
                        .addGap(0, 0, Short.MAX_VALUE))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(24, 24, 24)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(jLabel3)
                            .addComponent(jLabel4)
                            .addComponent(jLabel2, javax.swing.GroupLayout.Alignment.LEADING))
                        .addGap(30, 30, 30)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(DateFechaCarga_EditarCarga, javax.swing.GroupLayout.DEFAULT_SIZE, 153, Short.MAX_VALUE)
                            .addComponent(txtIdCarga_EditarCarga)
                            .addComponent(jComboPlacas_EditarCarga, 0, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                        .addGap(18, 18, 18)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(btAceptar_EditarCarga)
                            .addComponent(btSalir_EditarCarga, javax.swing.GroupLayout.Alignment.TRAILING))))
                .addContainerGap())
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel1)
                .addGap(26, 26, 26)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel2)
                    .addComponent(txtIdCarga_EditarCarga, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btAceptar_EditarCarga))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel3)
                    .addComponent(jComboPlacas_EditarCarga, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(22, 22, 22)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(jLabel4)
                            .addComponent(DateFechaCarga_EditarCarga, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(9, 9, 9)
                        .addComponent(btSalir_EditarCarga)))
                .addContainerGap(64, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btSalir_EditarCargaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btSalir_EditarCargaActionPerformed
       dispose();
    }//GEN-LAST:event_btSalir_EditarCargaActionPerformed

    private void btAceptar_EditarCargaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btAceptar_EditarCargaActionPerformed
        // TODO add your handling code here:
        Carga laCarga= new Carga();
        laCarga.setIdCamion(jComboPlacas_EditarCarga.getSelectedItem().toString());
        laCarga.setFechaCarga(ObtenerFecha());
        laCarga.setIdCarga(Integer.parseInt(txtIdCarga_EditarCarga.getText()));
        CoordinadorDeCamion elCoordinadorDeCamion= new CoordinadorDeCamion();
        try {
            boolean Exito=elCoordinadorDeCamion.EditarCarga(laCarga);
            if(Exito==false){
             getToolkit().beep();
            JOptionPane.showMessageDialog(null, "Se produjo un error a la hora de actualizar la carga");
            }else {
            JOptionPane.showMessageDialog(null, "Se edito con exito la carga");
            VisualizaryEditarCargas.ListarCargas();
            dispose();
            }
        } catch (ClassNotFoundException ex) {
            Logger.getLogger(EditarCarga.class.getName()).log(Level.SEVERE, null, ex);
        } catch (SQLException ex) {
            Logger.getLogger(EditarCarga.class.getName()).log(Level.SEVERE, null, ex);
        }
        

    }//GEN-LAST:event_btAceptar_EditarCargaActionPerformed

     public String ObtenerFecha() {

        SimpleDateFormat formatoDeFecha = new SimpleDateFormat("yyyy-MM-dd");
        return String.valueOf(formatoDeFecha.format(DateFechaCarga_EditarCarga.getDate()));
    }
    /**
     * @param args the command line arguments
     */
  

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private com.toedter.calendar.JDateChooser DateFechaCarga_EditarCarga;
    private javax.swing.JButton btAceptar_EditarCarga;
    private javax.swing.JButton btSalir_EditarCarga;
    public static javax.swing.JComboBox<String> jComboPlacas_EditarCarga;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JTextField txtIdCarga_EditarCarga;
    // End of variables declaration//GEN-END:variables
}
